easy_admin:
    formats:
        date:     'd/m/Y'           # Format d'affichage des dates
        time:     'H:i:s'           # Format d'affichage des heures/minutes/secondes
        datetime: 'd/m/Y H:i:s'     # Format d'affichage des datetime
    site_name: 'Gestion'    # Nom du backoffice, marqué en haut à gauche de l'interface
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"           # Active le thème de bootstrap 4 pour l'apparence des formulaires
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"     # Active le thème de ckeditor pour les champs ckeditor
        brand_color: 'blue'        # Couleur principale du backoffice (boutons, icônes, etc...)
        menu:       # Paramétrage du menu de gauche
            - { label: 'Revenir au site', route: 'main', icon: 'link'}     # Création d'un lien permettant de revenir sur le site sur l'accueil
            - { label: 'Ajouter un menu', route: 'createMenu', icon: 'plus'}     # Création d'un lien permettant de revenir sur le site sur l'accueil
            - Menu
    entities:
        Menu:
            class: App\Entity\Menu
            label: 'Gestion Menus'
            disabled_actions: ['new']
            edit:
                title: 'Modifier un menu'
                fields:
                    - {property: 'title', label: 'Titre'}
                    - {property: 'content', label: 'Contenu', type: 'fos_ckeditor'}
            list:
                sort: ['id', 'ASC']
                fields:
                    - {property: 'id', label: 'ID'}
                    - {property: 'title', label: 'Titre'}

        User:
            class: App\Entity\User